package com.example.repository;

import com.example.entity.User;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class UserRepositoryTest {

    @Autowired private TestEntityManager entityManager;
    @Autowired private UserRepository userRepository;

    @BeforeEach
    void setUp() {
        userRepository.deleteAll();
    }

    @AfterEach
    void tearDown() {
        userRepository.deleteAll();
    }

    @Test
    void save_ShouldPersistUserWithAutoGeneratedId() {
        User user = new User();
        user.setName("John");
        user.setEmail("john@example.com");
        user.setAge(25);

        User savedUser = userRepository.save(user);
        entityManager.flush();
        entityManager.clear();

        assertThat(savedUser.getId()).isNotNull();
        assertThat(savedUser.getCreatedAt()).isNotNull();

        User foundUser = entityManager.find(User.class, savedUser.getId());
        assertThat(foundUser).isNotNull();
        assertThat(foundUser.getName()).isEqualTo("John");
        assertThat(foundUser.getEmail()).isEqualTo("john@example.com");
        assertThat(foundUser.getAge()).isEqualTo(25);
    }

    @Test
    void findByEmail_ExistingEmail_ShouldReturnUser() {
        User user = createTestUser();

        Optional<User> foundUser = userRepository.findByEmail("john@example.com");

        assertThat(foundUser).isPresent();
        assertThat(foundUser.get().getId()).isEqualTo(user.getId());
        assertThat(foundUser.get().getEmail()).isEqualTo("john@example.com");
    }

    @Test
    void findAll_ShouldReturnAllUsers() {
        createTestUser();

        User user2 = new User();
        user2.setName("Alice");
        user2.setEmail("alice@example.com");
        user2.setAge(30);
        userRepository.save(user2);

        List<User> users = userRepository.findAll();

        assertThat(users).hasSize(2);
        assertThat(users)
                .extracting(User::getEmail)
                .containsExactlyInAnyOrder("john@example.com", "alice@example.com");
    }

    @Test
    void save_UserWithMaxLengthFields_WorksCorrectly() {
        User user = new User();
        user.setName("A".repeat(100));
        user.setEmail("a".repeat(50) + "@example.com");
        user.setAge(120);

        User saved = userRepository.save(user);
        entityManager.flush();

        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getName()).hasSize(100);
    }

    private User createTestUser() {
        User user = new User();
        user.setName("John");
        user.setEmail("john@example.com");
        user.setAge(25);
        return entityManager.persistAndFlush(user);
    }
}